server:
  port: 8088

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
     # discovery:
      #  locator:
       #   lower-case-service-id: true
      routes:
        - id: EMPLOYEE-SERVICE
          uri: http://localhost:9091
          predicates:
            - Path=/employees/**

        - id: PROJECT-SERVICE
          uri: http://localhost:9092
          predicates:
            - Path=/projects/**

        - id: client-service
          uri: http://localhost:9093
          predicates:
            - Path=/clients/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG